title:               haeeumm:ocean:'s Blog
email:              dhrgodms123@gmail.com
description:        I'am happy haeeun and this is my blog!
author:             Start Bootstrap
baseurl:            "/_blog"
url:                "https://dhrgodms.github.io"

# Social Profiles
github_username:    dhrgodms
instagram_username:  okhaeeun1, okhaeeun2, okhaeeun3
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
